name: fit_wallet
description: FitWallet — finanças rápidas. Registrar gastos diários com categorias mínimas.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_markdown: ^0.7.7+1
  flutter_native_splash: ^2.4.6
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.0.15
  url_launcher: ^6.3.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.0
  # use the packages you already had; add others as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_wallet_check.png
    - assets/splash.png
    - assets/images/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
